const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const http=require('node:http');
let server,browser;
const mime={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.png':'image/png','.svg':'image/svg+xml','.ttf':'font/ttf'};
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..'),qa=path.resolve(process.env.CCWA_SITE_QA||path.join(root,'.site-qa'));
(async()=>{fs.mkdirSync(qa,{recursive:true});server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(!pathname.startsWith('/cc-wire-analyzer/')){res.writeHead(404).end();return;}let file=path.resolve(root,'site',pathname.slice('/cc-wire-analyzer/'.length)||'index.html');if(!file.startsWith(path.join(root,'site')+path.sep)){res.writeHead(403).end();return;}try{if(fs.statSync(file).isDirectory())file=path.join(file,'index.html');res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port+'/cc-wire-analyzer/';const b=browser=await chromium.launch({headless:true}),p=await b.newPage({acceptDownloads:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));
for(const locale of ['en','zh']){const url=base+(locale==='zh'?'zh/':'');await p.goto(url);await p.evaluate(()=>document.fonts.ready);for(const img of await p.locator('img').all())await img.evaluate(i=>{i.loading="eager";return i.decode()});
for(const width of [1600,2560,390,320]){await p.setViewportSize({width,height:1000});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),locale+' '+width);await p.screenshot({path:path.join(qa,locale+'-'+width+'.png'),fullPage:true});}
for(let i=0;i<3;i++){await p.locator('#tab-'+i).click();assert(await p.locator('#example-'+i).isVisible());assert.equal(await p.locator('.example-panel:visible').count(),1);}
await p.locator('#tab-0').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#tab-1').getAttribute('aria-selected'),'true');await p.keyboard.press('End');assert(await p.locator('#tab-2').evaluate(e=>e===document.activeElement));
await p.locator('#example-2 .example-copy>a').click();await p.locator('#manual-dag > .content').waitFor({state:'visible'});await p.goBack();const download=p.waitForEvent('download');await p.locator('a[download]').click();const dl=await download;assert(fs.readFileSync(await dl.path()).equals(fs.readFileSync(path.join(root,'docs/product-manual.html'))));
await p.locator('.lang-link').click();assert.equal(await p.locator('html').getAttribute('lang'),locale==='zh'?'en':'zh-CN');}
const plain=await b.newPage({javaScriptEnabled:false});await plain.goto(base+'zh/');assert.equal(await plain.locator('.example-panel:visible').count(),3);await plain.close();assert.deepEqual(errors,[]);await b.close();server.close();fs.writeFileSync(path.join(qa,'report.json'),JSON.stringify({languages:2,widths:[1600,2560,390,320],errors,checks:['images decode','no horizontal overflow','tab click and keyboard','manual deep link','offline download byte equality','language switch','no-JS readable']},null,2));console.log('PASS: bilingual site, responsive layout, examples, manual deep links, offline download and no-JS reading');})().catch(e=>{console.error(e);if(server)server.close();if(browser)browser.close();process.exit(1)});
